for Cantonese use field_group = 'cantonese'
```
Anki 25.02.5 (29192d15)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.26100

Traceback (most recent call last):
  File "aqt.webview", line 188, in cmd
  File "aqt.webview", line 275, in _onCmd
  File "aqt.webview", line 803, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 92, in decorator_wrapper
  File "anki.hooks", line 87, in repl
  File "aqt.editor", line 421, in onBridgeCmd
  File "_aqt.hooks", line 2548, in __call__
  File "anki.hooks", line 48, in runFilter
  File "C:\Users\Michael\AppData\Roaming\Anki2\addons21\1752008591\edit.py", line 121, in onFocusLost
    if not update_fields(note, field, allFields):
  File "C:\Users\Michael\AppData\Roaming\Anki2\addons21\1752008591\behavior.py", line 351, in update_fields
    fill_color(hanzi, copy)
  File "C:\Users\Michael\AppData\Roaming\Anki2\addons21\1752008591\behavior.py", line 218, in fill_color
    field = get_first(config['fields'][field_group], note)
KeyError: 'jyutping'
```

Fixes the above error, the field for jyutping is called "cantonese", not "jyutping"